version: '2'

volumes:
  dev_mysql_data: {}
  dev_mysql_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: beep_dev_django
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.mysql
    ports:
      - 9000:8000
    command: ["/start"]

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    ports:
      - 3307:3306
    env_file:
      - ./.envs/.dev/.mysql
  
  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery:
    image: beep_dev_django
    command: celery -A config worker -l info -f logs/celery.log
    volumes:
      - .:/app
    depends_on:
      - redis
      - django


  # celery-beat:
  #   image: beep_dev_django
  #   command: celery -A config beat -l info -f logs/celery_beat.log
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #     - redis
