version: '2'

volumes:
  dev_mysql_data: {}
  dev_mysql_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: beep_dev_django
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.mysql
    ports:
      - 9000:8000
    command: ["/start"]

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    ports:
      - 3307:3306
    env_file:
      - ./.envs/.dev/.mysql
  
  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: beep_dev_django
    # command: celery -A config worker --concurrency=2 -l info -f logs/celery.log
    # command: celery -A config multi restart 4 --pidfile=logs/celery%n.pid -l info --logfile=logs/%n%I.log
    command: ["/app/compose/production/django/celery/woker/start"]
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.mysql
    depends_on:
      - redis
      - django

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: beep_dev_django
    # command: celery -A config beat -l info -f logs/celery_beat.log
    command: ["/app/compose/production/django/celery/beat/start"]
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.mysql
    depends_on:
      - redis
      - django
      - celery_worker

  celery_flower:
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: beep_dev_django
    # command: flower -A config  --address=0.0.0.0 --port=5555 --auto_refresh=True 
    command: ["/app/compose/production/django/celery/flower/start"]
    ports:
      - 5555:5555
    volumes:
      - .:/app
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.mysql
    depends_on:
      - redis
      - django
      - celery_worker
