version: '2'

services:
  
  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=2000
    restart: always
    expose:
      - "3306"
    ports:
      - 3307:3306
    env_file:
      - ./.envs/.production/.mysql

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beep_production_django
    restart: always
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    ports:
      - 9000:8000
    command: ["/start"]
    depends_on:
      - mysql
      - redis
      - celery_worker
      - celery_beat
      - celery_flower

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beep_production_django
    restart: always
    # command: celery -A config worker --concurrency=2 -l info -f logs/celery.log
    command: ["/app/compose/production/django/celery/woker/start"]    
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    depends_on:
      - redis
      - mysql

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beep_production_django
    restart: always
    # command: celery -A config beat -l info -f logs/celery_beat.log
    command: ["/app/compose/production/django/celery/beat/start"]    
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    depends_on:
      - redis
      - mysql
      - celery_worker

  celery_flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beep_production_django
    # command: flower -A config  --address=0.0.0.0 --port=5555 --auto_refresh=True --basic_auth=admin:888888 --log-file-prefix=logs/flower.log
    command: ["/app/compose/production/django/celery/flower/start"]
    ports:
      - 5555:5555
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    depends_on:
      - redis
      - mysql
      - celery_worker
      - celery_beat
