version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: beep_production_django
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    ports:
      - 9000:8000
    command: ["/start"]

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    expose:
      - "3306"
    ports:
      - 3307:3306
    env_file:
      - ./.envs/.production/.mysql
  
  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery:
    image: beep_production_django
    command: celery -A config worker -l info -f logs/celery.log
    volumes:
      - .:/app
    depends_on:
      - redis
      - django