# Generated by Django 2.2.5 on 2020-07-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(0, '博文评论'), (1, '活动评论')], default=0)),
                ('text', models.CharField(max_length=200, verbose_name='语句库')),
            ],
            options={
                'verbose_name': '评论库',
                'verbose_name_plural': '评论库',
                'db_table': 'cms_bot_commnet',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '停止'), (1, '运行中')], default=0, verbose_name='运行状态')),
                ('is_on', models.BooleanField(default=True, verbose_name='试用中')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '机器人',
                'verbose_name_plural': '机器人',
                'db_table': 'cms_bot',
                'ordering': ['-id'],
            },
        ),
    ]
