# Generated by Django 2.2.5 on 2020-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200702_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAvatarBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='输入导入数据【以换行符区分】')),
                ('done', models.BooleanField(default=False, verbose_name='执行成功')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '生成机器人头像批量生成',
                'verbose_name_plural': '生成机器人头像批量生成',
                'db_table': 'cms_bot_avatar_builder',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BotNameBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='输入导入数据【以换行符区分】')),
                ('done', models.BooleanField(default=False, verbose_name='执行成功')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '生成机器人姓名批量生成',
                'verbose_name_plural': '生成机器人姓名批量生成',
                'db_table': 'cms_bot_name_builder',
                'ordering': ['-id'],
            },
        ),
    ]
