# Generated by Django 2.2.5 on 2020-07-03 12:15

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botavatarbuilder_botnamebuilder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botavatarbuilder',
            name='text',
            field=models.TextField(verbose_name='输入导入数据【以换行符区分】'),
        ),
        migrations.AlterField(
            model_name='botbuilder',
            name='results',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[], verbose_name='机器人列表'),
        ),
        migrations.AlterField(
            model_name='botnamebuilder',
            name='text',
            field=models.TextField(verbose_name='输入导入数据【以换行符区分】'),
        ),
    ]
