# Generated by Django 2.2.5 on 2020-07-05 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20191202_1833'),
        ('activity', '0031_activity_poster'),
        ('bot', '0006_botactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotActionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_comment_activity', models.IntegerField(default=0, verbose_name='活动评论次数')),
                ('action_comment', models.IntegerField(default=0, verbose_name='评论次数')),
                ('action_forward', models.IntegerField(default=0, verbose_name='转发次数')),
                ('action_like', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('bots', django_extensions.db.fields.json.JSONField(blank=True, default=[], verbose_name='机器人user_id')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='博文')),
            ],
            options={
                'verbose_name': '机器人操作Blog统计',
                'verbose_name_plural': '机器人操作Blog统计',
                'db_table': 'cms_bot_action_stats',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='BotActionStatsOnBlog',
        ),
    ]
