# Generated by Django 2.2.5 on 2020-07-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200705_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botactionstats',
            old_name='action_comment_activity',
            new_name='action_activity_comment',
        ),
    ]
