# Generated by Django 2.2.5 on 2020-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20200706_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='任务名')),
                ('is_open', models.BooleanField(default=True, verbose_name='开启｜关闭')),
            ],
            options={
                'verbose_name': '机器人任务',
                'verbose_name_plural': '机器人任务',
                'db_table': 'cms_bot_task',
                'ordering': ['-id'],
            },
        ),
    ]
