# Generated by Django 2.2.5 on 2020-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_bottask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botactionlog',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, '博文评论'), (1, '博文点赞'), (2, '博文转发'), (3, '活动评论'), (4, '关注用户'), (5, '发博文增加关注')], default=0, verbose_name='行为'),
        ),
    ]
