# Generated by Django 2.2.5 on 2020-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_blogplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogplan',
            name='current',
            field=models.IntegerField(default=0, verbose_name='当前完成量'),
        ),
        migrations.AlterField(
            model_name='blogplan',
            name='total',
            field=models.IntegerField(default=0, verbose_name='目标多少'),
        ),
    ]
