# Generated by Django 2.2.5 on 2020-07-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20200716_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogplan',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
