# Generated by Django 2.2.5 on 2020-07-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_blogplan_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20, verbose_name='说明')),
                ('name', models.CharField(max_length=20, verbose_name='变量名')),
                ('value', models.CharField(max_length=200, verbose_name='值')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'cms_bot_setting',
                'ordering': ['-id'],
            },
        ),
    ]
