# Generated by Django 2.2.5 on 2020-07-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_botsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsetting',
            options={'ordering': ['-id'], 'verbose_name': '机器人系统设置', 'verbose_name_plural': '系统设置'},
        ),
    ]
