# Generated by Django 2.2.5 on 2020-07-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20200718_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botsetting',
            options={'ordering': ['-id'], 'verbose_name': '机器人系统设置', 'verbose_name_plural': '机器人系统设置'},
        ),
    ]
