# Generated by Django 2.2.5 on 2019-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('origin', models.CharField(blank=True, max_length=40, verbose_name='来源')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '编辑中'), (1, '已发布'), (2, '已撤回')], default=0, verbose_name='编辑状态')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
