# Generated by Django 2.2.5 on 2019-10-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '快讯', 'verbose_name_plural': '快讯'},
        ),
    ]
