# Generated by Django 2.2.5 on 2019-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191024_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120, verbose_name='网站名')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('published_at', models.BigIntegerField(default=0, verbose_name='发布时间')),
                ('source', models.CharField(max_length=200, verbose_name='爬取原始平台')),
                ('link', models.CharField(default='', max_length=200, verbose_name='原始链接')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('md5_content', models.CharField(max_length=120, verbose_name='内容md5')),
            ],
            options={
                'db_table': 'crawled_document',
            },
        ),
    ]
