# Generated by Django 2.2.5 on 2019-11-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_crawleddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawleddocument',
            name='crawled_at',
            field=models.DateTimeField(null=True, verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='crawleddocument',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
    ]
