# Generated by Django 2.2.5 on 2019-11-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191105_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawleddocument',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='crawleddocument',
            name='is_news',
            field=models.BooleanField(default=False, verbose_name='更新到news'),
        ),
    ]
