# Generated by Django 2.2.5 on 2019-11-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191112_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120, verbose_name='网站名')),
                ('auto_news', models.BooleanField(default=False, verbose_name='自动同步')),
            ],
            options={
                'db_table': 'spider_config',
                'ordering': ['-id'],
            },
        ),
    ]
