# Generated by Django 2.2.5 on 2020-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_skuexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuexchange',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='消耗积分'),
        ),
    ]
