# Generated by Django 2.2.5 on 2020-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200110_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuproperty',
            name='property_name_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='属性名2'),
        ),
        migrations.AlterField(
            model_name='skuproperty',
            name='property_name_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='属性名3'),
        ),
        migrations.AlterField(
            model_name='skuproperty',
            name='property_value_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='属性值2'),
        ),
        migrations.AlterField(
            model_name='skuproperty',
            name='property_value_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='属性值3'),
        ),
    ]
