# Generated by Django 2.2.5 on 2020-01-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200110_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skuproperty',
            options={'ordering': ['-id'], 'verbose_name': '商品属性', 'verbose_name_plural': '商品属性'},
        ),
        migrations.AlterModelOptions(
            name='skupropertyname',
            options={'ordering': ['-id'], 'verbose_name': '商品属性名', 'verbose_name_plural': '商品属性名'},
        ),
        migrations.AlterModelOptions(
            name='skutype',
            options={'ordering': ['-id'], 'verbose_name': '商品类型', 'verbose_name_plural': '商品类型'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(max_length=120, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='skuexchange',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Sku', verbose_name='积分商品'),
        ),
        migrations.AlterField(
            model_name='skuproperty',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Sku', verbose_name='商品'),
        ),
    ]
