# Generated by Django 2.2.5 on 2020-01-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200110_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='sku_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SkuType', verbose_name='类型'),
        ),
    ]
