# Generated by Django 2.2.5 on 2020-01-11 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_auto_20200111_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Sku', verbose_name='商品')),
                ('sku_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SkuProperty', verbose_name='商品属性')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'beep_sku_cart',
                'ordering': ['-create_at'],
                'unique_together': {('user', 'sku', 'sku_property')},
            },
        ),
    ]
