# Generated by Django 2.2.5 on 2020-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_skucart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuorder',
            name='order_num',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='订单号'),
        ),
    ]
