# Generated by Django 2.2.5 on 2020-01-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200111_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['order_num', '-create_at'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='skuorder',
            name='user_del',
            field=models.BooleanField(default=False, verbose_name='已删除[用户]'),
        ),
    ]
