# Generated by Django 2.2.5 on 2020-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200111_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skupropertyname',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='属性名称'),
        ),
    ]
