# Generated by Django 2.2.5 on 2020-01-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_sku_is_recommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='简介'),
        ),
    ]
