# Generated by Django 2.2.5 on 2019-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='个人简介'),
        ),
    ]
