# Generated by Django 2.2.5 on 2019-10-20 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191013_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='LableApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lebel_type', models.PositiveSmallIntegerField(choices=[(0, '红V'), (1, '蓝V')], default=0, verbose_name='红V|蓝V')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='证件照')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('data_dict', django_extensions.db.fields.json.JSONField(default='{"total_view": 0, "total_followers": 0, "total_blog": 0}', verbose_name='数据信息')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '已提交'), (1, '审核通过'), (2, '审核失败')], default=0, verbose_name='审核状态')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'label_apply',
                'ordering': ['-create_at'],
            },
        ),
    ]
