# Generated by Django 2.2.5 on 2019-10-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lableapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='label_type',
            field=models.PositiveIntegerField(choices=[(0, '普通用户'), (1, '红V'), (2, '蓝V')], default=0, verbose_name='普通用户|红V|蓝V'),
        ),
        migrations.AlterField(
            model_name='lableapply',
            name='lebel_type',
            field=models.PositiveSmallIntegerField(choices=[(0, '普通用户'), (1, '红V'), (2, '蓝V')], default=1, verbose_name='红V|蓝V'),
        ),
    ]
