# Generated by Django 2.2.5 on 2019-10-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191021_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='昵称'),
        ),
    ]
