# Generated by Django 2.2.5 on 2019-10-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191021_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lableapply',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='证件照'),
        ),
    ]
