# Generated by Django 2.2.5 on 2019-11-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191026_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-create_at']},
        ),
    ]
