# Generated by Django 2.2.5 on 2019-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191106_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='头像'),
        ),
    ]
