# Generated by Django 2.2.5 on 2019-11-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_auto_20191120_2041'),
        ('users', '0011_auto_20191107_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lableapply',
            options={'ordering': ['-create_at'], 'verbose_name': '加V申请', 'verbose_name_plural': '加V申请'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'activity')},
        ),
    ]
