# Generated by Django 2.2.5 on 2019-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191121_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
