# Generated by Django 2.2.5 on 2019-11-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unionid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信unionid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mini_openid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='小程序账号'),
        ),
    ]
