# Generated by Django 2.2.5 on 2020-01-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-create_at'], 'verbose_name': '用户积分', 'verbose_name_plural': '用户积分'},
        ),
        migrations.AddField(
            model_name='user',
            name='completed_profile',
            field=models.BooleanField(default=False, verbose_name='完善信息'),
        ),
        migrations.AlterField(
            model_name='point',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, '每日签到'), (1, '兑换商品消费'), (2, '兑换商品退回'), (1001, '用户注册'), (1002, '用户完善个人信息'), (2001, '每日首评'), (2002, '发表博文'), (2003, '发布话题'), (2004, '参与话题'), (3001, '邀请用户注册')], default=0, verbose_name='原因'),
        ),
    ]
