# Generated by Django 2.2.5 on 2020-01-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200107_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='邀请码'),
        ),
    ]
