# Generated by Django 2.2.5 on 2020-01-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_invite_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileCompleted',
        ),
    ]
