# Generated by Django 2.2.5 on 2020-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_userprofilecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, '每日签到'), (1, '兑换商品消费'), (2, '兑换商品退回'), (1001, '用户注册'), (1002, '用户完善个人信息'), (2001, '每日首评'), (2002, '发表博文'), (2003, '发布话题'), (2004, '参与话题'), (2005, '博文点赞'), (2006, '博文评论'), (2007, '博文转发'), (3001, '邀请用户注册')], default=0, verbose_name='原因'),
        ),
    ]
