# Generated by Django 2.2.5 on 2020-03-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200323_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='已读'),
        ),
    ]
