# Generated by Django 2.2.5 on 2020-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_point_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, verbose_name='机器人账号'),
        ),
    ]
