# Generated by Django 2.2.5 on 2020-07-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200706_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('user', 'following')},
        ),
        migrations.AlterIndexTogether(
            name='relationship',
            index_together={('user', 'following')},
        ),
    ]
