# Generated by Django 2.2.5 on 2020-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200706_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBot',
            fields=[
            ],
            options={
                'verbose_name': '机器人账号',
                'verbose_name_plural': '机器人账号',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='UserInner',
            fields=[
            ],
            options={
                'verbose_name': '内部运营人员使用账号',
                'verbose_name_plural': '内部运营人员使用账号',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='is_inner',
            field=models.BooleanField(blank=True, default=False, verbose_name='内部运营人员使用账号'),
        ),
    ]
