# Generated by Django 2.2.5 on 2019-10-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=200, unique=True, verbose_name='wxid')),
                ('wx_alias', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信号')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='微信昵称')),
                ('head_img', models.CharField(blank=True, max_length=200, null=True, verbose_name='头像的url地址')),
                ('nonce', models.CharField(blank=True, max_length=200, null=True, verbose_name='nonce')),
                ('client_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='client_version')),
                ('machine_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='machine_id')),
                ('local_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='local_ip')),
            ],
            options={
                'db_table': 'wx_bot',
            },
        ),
    ]
