# Generated by Django 2.2.5 on 2019-10-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0002_wxbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxgroup',
            name='bot_wxid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bot_wxid'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='bot_wxid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='bot_wxid'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='wxid',
            field=models.CharField(max_length=200, verbose_name='wxid'),
        ),
        migrations.AlterUniqueTogether(
            name='wxgroup',
            unique_together={('wxid', 'bot_wxid')},
        ),
        migrations.AlterUniqueTogether(
            name='wxuser',
            unique_together={('wxid', 'bot_wxid')},
        ),
    ]
