# Generated by Django 2.2.5 on 2019-10-28 08:53

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0003_auto_20191028_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxgroup',
            name='memberInfo_list',
            field=django_extensions.db.fields.json.JSONField(default='[]', verbose_name='当前群的成员信息列表'),
        ),
    ]
