# Generated by Django 2.2.5 on 2019-10-28 14:30

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0004_wxgroup_memberinfo_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=200, verbose_name='id')),
                ('msg_timestamp', models.CharField(blank=True, max_length=200, null=True, verbose_name='时间戳')),
                ('msg_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='类型')),
                ('room_wxid', models.CharField(blank=True, max_length=200, null=True, verbose_name='群wxid')),
                ('wxid_from', models.CharField(blank=True, max_length=200, null=True, verbose_name='发送人')),
                ('wxid_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='接收人')),
                ('atUserList', django_extensions.db.fields.json.JSONField(default='[]', verbose_name='@用户列表')),
                ('msg', models.CharField(blank=True, max_length=2000, null=True, verbose_name='文本内容')),
                ('raw_msg', models.CharField(blank=True, max_length=2000, null=True, verbose_name='微信原始消息')),
                ('file_index', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片文件索引')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片文件名')),
                ('file_size', models.FloatField(default=0, verbose_name='文件大小')),
                ('emoji_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='表情')),
                ('link_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('link_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题')),
                ('link_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接')),
                ('link_img_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接所列图地址')),
                ('bot_wxid', models.CharField(blank=True, max_length=200, null=True, verbose_name='bot_wxid')),
            ],
            options={
                'db_table': 'wx_message',
            },
        ),
    ]
