# Generated by Django 2.2.5 on 2019-10-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0005_wxmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxmessage',
            name='msg_timestamp',
            field=models.PositiveIntegerField(default=0, verbose_name='时间戳'),
        ),
    ]
