# Generated by Django 2.2.5 on 2019-10-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0008_auto_20191030_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxmessage',
            options={'ordering': ['-create_at']},
        ),
        migrations.AddField(
            model_name='wxmessage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='wxmessage',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='平台用户user_id'),
        ),
        migrations.AddField(
            model_name='wxmessage',
            name='user_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='用户类型：0:微信用户， 1:平台用户'),
        ),
        migrations.AlterField(
            model_name='wxmessage',
            name='msg',
            field=models.TextField(blank=True, null=True, verbose_name='文本内容（平台消息）'),
        ),
        migrations.AlterField(
            model_name='wxmessage',
            name='msg_id',
            field=models.CharField(max_length=200, verbose_name='msg_id'),
        ),
        migrations.AlterField(
            model_name='wxmessage',
            name='raw_msg',
            field=models.TextField(blank=True, null=True, verbose_name='微信原始消息（平台消息）'),
        ),
    ]
