# Generated by Django 2.2.5 on 2019-10-30 16:13

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0009_auto_20191030_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxmessage',
            options={'ordering': ['-msg_timestamp']},
        ),
        migrations.AlterField(
            model_name='wxmessage',
            name='atUserList',
            field=django_extensions.db.fields.json.JSONField(blank=True, default='[]', verbose_name='@用户列表'),
        ),
        migrations.AlterField(
            model_name='wxmessage',
            name='msg_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='时间戳(毫秒)'),
        ),
    ]
