# Generated by Django 2.2.5 on 2019-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0010_auto_20191031_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxmessage',
            name='sub_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='/链接消息的子类型'),
        ),
    ]
