# Generated by Django 2.2.5 on 2019-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0011_wxmessage_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxmessage',
            name='user_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='用户类型：0:微信用户， 1:平台用户, 2:系统消息'),
        ),
    ]
