# Generated by Django 2.2.5 on 2019-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0014_auto_20191205_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxgroup',
            name='room_wxid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='群wxid'),
        ),
    ]
