# Generated by Django 2.2.5 on 2020-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_callback', '0017_auto_20191212_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxmessage',
            name='activity_id',
            field=models.PositiveIntegerField(default=0, verbose_name='活动id'),
        ),
    ]
