# Generated by Django 2.2.5 on 2019-11-23 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0026_auto_20191123_1600'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_auto_20191112_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名')),
                ('code', models.CharField(max_length=64, verbose_name='模板id')),
                ('vars_list', django_extensions.db.fields.json.JSONField(blank=True, default='[]', verbose_name='变量名列表')),
            ],
            options={
                'verbose_name': '订阅消息模板',
                'verbose_name_plural': '订阅消息模板',
                'db_table': 'wx_templates',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WxSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('wx_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.WxTemplate', verbose_name='订阅消息模板')),
            ],
            options={
                'verbose_name': '消息订阅',
                'verbose_name_plural': '消息订阅',
                'db_table': 'wx_subscriptions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WxSubMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未发送'), (1, '已发送')], default=0, verbose_name='已发送')),
                ('data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, verbose_name='post.body')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='活动')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.News', verbose_name='快讯')),
                ('wx_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wechat.WxTemplate', verbose_name='模板消息')),
            ],
            options={
                'verbose_name': '订阅消息推送',
                'verbose_name_plural': '订阅消息推送',
                'db_table': 'wx_submessages',
                'ordering': ['-id'],
            },
        ),
    ]
