# Generated by Django 2.2.5 on 2019-11-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20191117_2311'),
        ('wechat', '0002_auto_20191124_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxsubmessage',
            name='hotsearch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.HotSearch', verbose_name='热搜'),
        ),
        migrations.AddField(
            model_name='wxsubmessage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='热搜标题'),
        ),
        migrations.AddField(
            model_name='wxsubmessage',
            name='warn_msg',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='温馨提示'),
        ),
        migrations.AddField(
            model_name='wxtemplate',
            name='tpl_id',
            field=models.PositiveIntegerField(default=0, verbose_name='模板编号'),
        ),
    ]
