# Generated by Django 2.2.5 on 2019-11-24 16:22

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20191124_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxtemplate',
            name='vars_list',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, verbose_name='变量名列表'),
        ),
    ]
