# Generated by Django 2.2.5 on 2019-11-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20191124_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxsubmessage',
            name='activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='wxsubmessage',
            name='hotsearch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.HotSearch', verbose_name='热搜'),
        ),
    ]
