# Generated by Django 2.2.5 on 2019-11-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchkeyword',
            options={'ordering': ['-create_date', '-frequency'], 'verbose_name': '搜索关键词', 'verbose_name_plural': '搜索关键词'},
        ),
    ]
