# Generated by Django 2.2.5 on 2019-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_hotsearch_searchtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtask',
            name='create_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='searchtask',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
