# Generated by Django 2.2.5 on 2019-11-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191107_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsearch',
            options={'ordering': ['-task', '-update_at', '-frequency'], 'verbose_name': '热搜榜', 'verbose_name_plural': '热搜榜'},
        ),
        migrations.AlterModelOptions(
            name='searchkeyword',
            options={'ordering': ['-create_at', '-frequency'], 'verbose_name': '搜索关键词', 'verbose_name_plural': '搜索关键词'},
        ),
        migrations.RenameField(
            model_name='searchkeyword',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.AlterUniqueTogether(
            name='searchkeyword',
            unique_together={('keyword', 'create_at')},
        ),
    ]
