# Generated by Django 2.2.5 on 2019-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191107_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtask',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='searchtask',
            name='status',
            field=models.PositiveIntegerField(default=0, verbose_name='开始|完成|失败'),
        ),
    ]
