# Generated by Django 2.2.5 on 2019-11-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20191108_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsearch',
            options={'ordering': ['-is_top', '-task_id', '-update_at', '-frequency'], 'verbose_name': '热搜榜', 'verbose_name_plural': '热搜榜'},
        ),
    ]
