# Generated by Django 2.2.5 on 2020-01-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPointCfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=0, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='行为')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='奖励积分')),
                ('is_on', models.BooleanField(default=True, verbose_name='应用中')),
            ],
            options={
                'db_table': 'beep_action_point_cfg',
            },
        ),
    ]
