# Generated by Django 2.2.5 on 2020-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0003_auto_20200107_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpointcfg',
            name='max_per_day',
            field=models.PositiveIntegerField(default=1000, verbose_name='每天获取积分上限'),
        ),
    ]
