# Generated by Django 2.2.5 on 2019-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_view',
            field=models.PositiveIntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
