# Generated by Django 2.2.5 on 2019-09-24 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blog_total_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='topic',
            name='total_comment',
            field=models.PositiveIntegerField(default=0, verbose_name='评论次数'),
        ),
        migrations.AddField(
            model_name='topic',
            name='total_view',
            field=models.PositiveIntegerField(default=0, verbose_name='查看人数'),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
