# Generated by Django 2.2.5 on 2019-10-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190925_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_group', to='blog.Comment', verbose_name='回复消息的一级id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_real', to='blog.Comment', verbose_name='回复消息id'),
        ),
    ]
