# Generated by Django 2.2.5 on 2019-10-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191018_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_forward',
            field=models.PositiveIntegerField(default=0, verbose_name='转发次数'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
