# Generated by Django 2.2.5 on 2019-10-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191020_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
