# Generated by Django 2.2.5 on 2019-10-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-update_at'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '话题|专题|新人榜', 'verbose_name_plural': '话题|专题|新人榜'},
        ),
    ]
