# Generated by Django 2.2.5 on 2019-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文章封面图'),
        ),
    ]
