# Generated by Django 2.2.5 on 2019-10-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20191024_2013'),
        ('blog', '0014_auto_20191024_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity', verbose_name='活动'),
        ),
    ]
