# Generated by Django 2.2.5 on 2019-11-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191030_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_at'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-create_at'], 'verbose_name': '话题|专题|新人榜', 'verbose_name_plural': '话题|专题|新人榜'},
        ),
        migrations.AddField(
            model_name='blog',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序值[越大越靠前]'),
        ),
    ]
