# Generated by Django 2.2.5 on 2019-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20191101_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序值[越小越靠前]'),
        ),
    ]
