# Generated by Django 2.2.5 on 2019-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20191101_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sub_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='子话题'),
        ),
    ]
