# Generated by Django 2.2.5 on 2019-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_topic_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='sub_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='子话题'),
        ),
    ]
