# Generated by Django 2.2.5 on 2019-11-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191105_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_num', '-create_at'], 'verbose_name': '话题|专题|新人榜', 'verbose_name_plural': '话题|专题|新人榜'},
        ),
        migrations.AddField(
            model_name='topic',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='排序值[越小越靠前]'),
        ),
    ]
