# Generated by Django 2.2.5 on 2019-11-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_topic_total_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_blog',
            field=models.PositiveIntegerField(default=0, verbose_name='博文数量'),
        ),
    ]
