# Generated by Django 2.2.5 on 2019-11-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20191110_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_summary',
            field=models.BooleanField(default=False, verbose_name='活动总结博文'),
        ),
    ]
