# Generated by Django 2.2.5 on 2019-11-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_blog_is_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未读'), (0, '已读')], default=0, verbose_name='未|已读'),
        ),
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未读'), (0, '已读')], default=0, verbose_name='未|已读'),
        ),
    ]
