# Generated by Django 2.2.5 on 2019-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20191115_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Article',
            fields=[
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blog',),
        ),
        migrations.CreateModel(
            name='Blog_Blog',
            fields=[
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blog',),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
