# Generated by Django 2.2.5 on 2019-11-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20191118_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_anonymous',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否匿名'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_summary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='活动总结博文'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否置顶'),
        ),
    ]
