# Generated by Django 2.2.5 on 2019-09-20 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('cover', models.ImageField(max_length=200, upload_to='', verbose_name='封面图')),
                ('activity_type', models.PositiveSmallIntegerField(choices=[(0, '线上'), (1, '线下')], default=0, verbose_name='活动类型')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('ticket_price', models.FloatField(default=0, verbose_name='费用（元）')),
                ('address', models.CharField(max_length=120, verbose_name='具体位置信息')),
                ('live_plateform', models.CharField(blank=True, max_length=120, verbose_name='直播平台')),
                ('live_address', models.CharField(blank=True, max_length=20, verbose_name='直播地址|微信群名')),
                ('total_user', models.PositiveIntegerField(default=0, verbose_name='活动人数')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_info', models.CharField(max_length=100, verbose_name='联系人电话|微信')),
                ('total_view', models.PositiveIntegerField(default=0, verbose_name='查看人数')),
                ('total_registration', models.PositiveIntegerField(default=0, verbose_name='报名个数')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Area', verbose_name='区域')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '成功')], default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'db_table': 'registration',
                'unique_together': {('user', 'activity')},
                'index_together': {('user', 'activity')},
            },
        ),
    ]
