# Generated by Django 2.2.5 on 2019-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.TextField(blank=True, verbose_name='活动详情'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cover',
            field=models.CharField(max_length=200, verbose_name='封面图'),
        ),
    ]
