# Generated by Django 2.2.5 on 2019-10-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20191009_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-create_at']},
        ),
    ]
