# Generated by Django 2.2.5 on 2019-10-13 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0003_auto_20191013_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_collect',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='博客')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'activity_collect',
                'ordering': ['-create_at'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
