# Generated by Django 2.2.5 on 2019-10-29 16:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_blog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_at'], 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AddField(
            model_name='activity',
            name='wx_groupid',
            field=models.CharField(blank=True, max_length=200, verbose_name='微信群id[后台获取]'),
        ),
        migrations.AddField(
            model_name='activity',
            name='wx_groupname',
            field=models.CharField(blank=True, max_length=200, verbose_name='微信群名[后台获取]'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='活动详情'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cover',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='封面图'),
        ),
    ]
