# Generated by Django 2.2.5 on 2019-10-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20191030_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='wx_groupid',
        ),
        migrations.AddField(
            model_name='activity',
            name='wx_botwxid',
            field=models.CharField(blank=True, max_length=200, verbose_name='微信机器人wxid[后台获取]'),
        ),
        migrations.AddField(
            model_name='activity',
            name='wx_groupwxid',
            field=models.CharField(blank=True, max_length=200, verbose_name='微信群wxid[后台获取]'),
        ),
    ]
