# Generated by Django 2.2.5 on 2019-11-01 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0011_activity_ask_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100, verbose_name='代币名称')),
                ('coin_logo', models.ImageField(upload_to='', verbose_name='代币logo')),
                ('total_coin', models.IntegerField(default=0, verbose_name='代币数量')),
                ('total_luckyuser', models.IntegerField(default=0, verbose_name='中奖人数')),
                ('start_time', models.DateTimeField(verbose_name='开奖时间')),
                ('result', django_extensions.db.fields.json.JSONField(blank=True, default='[]', verbose_name='中奖信息')),
            ],
            options={
                'verbose_name': '活动空投',
                'verbose_name_plural': '活动空投',
                'db_table': 'activity_reward',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RewardPlanApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='收币地址')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否中奖')),
                ('activity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity', verbose_name='活动')),
                ('rewardplan', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.RewardPlan', verbose_name='空投')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
            ],
            options={
                'db_table': 'activity_reward_apply',
                'ordering': ['-activity', '-create_at'],
                'unique_together': {('user', 'rewardplan', 'activity')},
            },
        ),
        migrations.AddField(
            model_name='rewardplan',
            name='applyers',
            field=models.ManyToManyField(blank=True, through='activity.RewardPlanApply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='rewardplan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.RewardPlan', verbose_name='空投'),
        ),
    ]
