# Generated by Django 2.2.5 on 2019-11-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20191102_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardplan',
            name='desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=120, verbose_name='具体位置信息'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人电话|微信'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ticket_price',
            field=models.FloatField(blank=True, default=0, verbose_name='费用（元）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_user',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='活动人数'),
        ),
    ]
