# Generated by Django 2.2.5 on 2019-11-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20191102_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardplanapply',
            options={'ordering': ['-activity', '-create_at'], 'verbose_name': '活动空投报名', 'verbose_name_plural': '活动空投报名'},
        ),
    ]
