# Generated by Django 2.2.5 on 2019-11-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20191106_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardplanapply',
            name='activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='rewardplanapply',
            name='rewardplan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.RewardPlan', verbose_name='空投'),
        ),
    ]
