# Generated by Django 2.2.5 on 2019-11-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_auto_20191107_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rewardplan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.RewardPlan', verbose_name='空投'),
        ),
    ]
