# Generated by Django 2.2.5 on 2019-11-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_activity_summary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='registration',
            name='company',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='手机号'),
        ),
    ]
