# Generated by Django 2.2.5 on 2019-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_auto_20191117_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_recommand',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
