# Generated by Django 2.2.5 on 2019-11-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_activity_is_recommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='coordinates',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='经度,纬度'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_recommand',
            field=models.BooleanField(blank=True, default=False, verbose_name='推荐'),
        ),
    ]
