# Generated by Django 2.2.5 on 2019-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_collected',
            field=models.BooleanField(default=False, verbose_name='活动收藏'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_registrated',
            field=models.BooleanField(default=False, verbose_name='活动报名'),
        ),
    ]
