# Generated by Django 2.2.5 on 2019-11-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_auto_20191121_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-plan_datetime', '-id']},
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '正在审核'), (1, '审核通过'), (2, '正在失败')], default=0, verbose_name='审核状态'),
        ),
    ]
