# Generated by Django 2.2.5 on 2019-11-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0024_auto_20191123_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxform_id', models.CharField(max_length=32, verbose_name='wxform_id')),
                ('published', models.BooleanField(default=False, verbose_name='已推送')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Activity', verbose_name='活动')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信form',
                'verbose_name_plural': '微信form',
                'db_table': 'activity_wxform',
                'ordering': ['-id'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
