# Generated by Django 2.2.5 on 2019-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_auto_20191123_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardplan',
            name='coin_logo',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='代币logo'),
        ),
    ]
