# Generated by Django 2.2.5 on 2019-11-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_auto_20191125_0204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WxForm',
        ),
    ]
