# Generated by Django 2.2.5 on 2019-12-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_delete_wxform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动'),
        ),
    ]
